--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    - 
      ec2_instance: 
        image_id: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ ami_type }}', region='us-east-1') }}"
        instance_role: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ instance_role }}', region='us-east-1') }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/keyname', region='us-east-1') }}"
        name: "{{ instance_name }}"
        region: us-east-1
        security_group: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ security_group }}', region='us-east-1') }}"
        tags: 
          App_Name: "{{ App_Name }}"
          Business_Unit: "{{ Business_Unit }}"
          Cost_Center: "{{ Cost_Center }}"
          Owner: "{{ Owner }}"
          created_by: "{{ created_by }}"
        user_data: |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
            echo "<html><body><h1>Hello JJTech Team</h1></body></html>" > /var/www/html/index.html
        volumes: 
          - 
            device_name: /dev/xvda
            ebs: 
              delete_on_termination: true
              encrypted: true
              volume_size: "{{ root_volume_size }}"
              volume_type: gp2
        vpc_subnet_id: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ vpc_subnet_id }}', region='us-east-1') }}"
        wait: true
      name: "Create EC2"
